### PR TITLE
Fetch UART data from the sensor using an arduino

### PR DESCRIPTION
**Pull request by TsarF**
yeah

Things todo:
Make I2C slave
Find out why in the world the value is always -1,696,464,896‬ on both X and Y motion
Integrate
Filter
The usual

### CODE REVIEW

**Review by HoldenA1 — DISMISSED** [review]
Looks like cancer

**Review by ArgyleSocks — DISMISSED** [review]
Looks solid, we should test this on 1/24 in class and then merge it (just to be certain that we can mount it with the team hardware).

**Review by Maciej4 — DISMISSED** [review]
Fix merge conflicts and you are good

**Review by Maciej4 — APPROVED** [review]
Everything looks good.

**Pull request merged**
