### PR TITLE
Alignment test pull

### PR DESCRIPTION
**Pull request by AlexanderFairchild**
adds alignment test and small fixes to remove build-blocking errors.

### CODE REVIEW

**Review by HoldenA1 — CHANGES_REQUESTED** [review]
Not to be annoying about it, but please move opening curly braces to the same line as the function declaration. In addition, assertEquals should be used with the expected first and actual (the value you are testing).

**Comment by AlexanderFairchild** [comment]
Thanks for the feedback, should be good in those regards now. Let me know if there's anything else that I missed.

**Review by HoldenA1 — DISMISSED** [review]

**Comment by AlexanderFairchild** [comment]
Resolved merge conflicts

**Review by ArgyleSocks — APPROVED** [review]
Looks fine, approved.

**Pull request merged**
