### PR TITLE
cleanup autogen files and update .gitignore

### PR DESCRIPTION
**Pull request by Maciej4**
This pull request is made in order to remove the autogen files which should not be stored on  the master branch.

### CODE REVIEW

**Comment by Maciej4** [comment]
This should be tested before the pull request is accepted. I would recommend downloading and building this branch to see if it builds successfully and regenerates the files.

**Comment by Maciej4** [comment]
Ideally it regenerates the files and builds successfully and the changes are not visible in github desktop.

**Comment by Maciej4** [comment]
One final note, in the commit "remove autogen files" I have edited the .wpilib preferences file by adding changing the language from "none" to "java". Hopefully this change removes the language selection  screen when building/deploying and saves time.

**Review by HoldenA1 — DISMISSED** [review]

**Comment by Maciej4** [comment]
Yup, that is why we test things

**Review by HoldenA1 — APPROVED** [review]
Problem was with ShooterController class, and the problem is in master too. This code wasn't the problem.

**Pull request merged**
